/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yjgAka4UecP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function home() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center justify-between">
        <Link href="#" className="flex items-center" prefetch={false}>
          <span className="text-lg font-bold">Jane Doe</span>
        </Link>
        <nav className="hidden lg:flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Portfolio
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section id="about" className="w-full py-12 md:py-24 lg:py-32 bg-background">
          <div className="container px-4 md:px-6 grid gap-8 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Hi, I'm Jane Doe</h1>
              <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed">
                I'm an architecture student passionate about designing innovative and sustainable spaces. My portfolio
                showcases a range of projects that demonstrate my creativity, technical skills, and attention to detail.
              </p>
            </div>
            <img
              src="/placeholder.svg"
              width="550"
              height="550"
              alt="Hero"
              className="mx-auto aspect-square overflow-hidden rounded-xl object-cover sm:w-full"
            />
          </div>
        </section>
        <section id="portfolio" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6 space-y-8">
            <div className="space-y-4 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Portfolio</h2>
              <p className="max-w-[600px] mx-auto text-muted-foreground md:text-xl/relaxed">
                Explore a selection of my architecture projects, showcasing my design skills and creative approach.
              </p>
            </div>
            <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3">
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="400"
                  alt="Project 1"
                  className="aspect-[4/3] w-full object-cover transition-all group-hover:scale-105"
                />
                <div className="absolute inset-0 bg-black/50 flex flex-col items-center justify-center p-4 text-center opacity-0 group-hover:opacity-100 transition-opacity">
                  <h3 className="text-lg font-bold text-white">Project 1</h3>
                  <p className="text-sm text-white/80 mt-2">
                    A sustainable residential design with a focus on natural lighting and energy efficiency.
                  </p>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="400"
                  alt="Project 2"
                  className="aspect-[4/3] w-full object-cover transition-all group-hover:scale-105"
                />
                <div className="absolute inset-0 bg-black/50 flex flex-col items-center justify-center p-4 text-center opacity-0 group-hover:opacity-100 transition-opacity">
                  <h3 className="text-lg font-bold text-white">Project 2</h3>
                  <p className="text-sm text-white/80 mt-2">
                    A mixed-use development with a focus on urban planning and community integration.
                  </p>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="400"
                  alt="Project 3"
                  className="aspect-[4/3] w-full object-cover transition-all group-hover:scale-105"
                />
                <div className="absolute inset-0 bg-black/50 flex flex-col items-center justify-center p-4 text-center opacity-0 group-hover:opacity-100 transition-opacity">
                  <h3 className="text-lg font-bold text-white">Project 3</h3>
                  <p className="text-sm text-white/80 mt-2">
                    A commercial office design with a focus on employee well-being and productivity.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="contact" className="w-full py-12 md:py-24 lg:py-32 bg-background">
          <div className="container px-4 md:px-6 space-y-8">
            <div className="space-y-4 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Get in Touch</h2>
              <p className="max-w-[600px] mx-auto text-muted-foreground md:text-xl/relaxed">
                I'd love to hear from you! Feel free to reach out with any questions or inquiries about my work.
              </p>
            </div>
            <form className="mx-auto max-w-md space-y-4">
              <Input type="text" placeholder="Name" className="w-full" />
              <Input type="email" placeholder="Email" className="w-full" />
              <Textarea placeholder="Message" rows={5} className="w-full" />
              <Button type="submit" className="w-full">
                Submit
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Jane Doe. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy Policy
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
        </nav>
      </footer>
    </div>
  )
}
